name: configlet
on: [push, pull_request]

jobs:
  configlet-lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Install configlet
      uses: exercism/github-actions/configlet-ci@main

    - name: configlet lint
      run: configlet lint
